import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function formatDateValue(value) {
  return new Intl.DateTimeFormat("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric"
  }).format(value);
}

function formatTimeValue(value) {
  return new Intl.DateTimeFormat("en-IN", {
    hour: "2-digit",
    minute: "2-digit"
  }).format(value);
}

function formatFileDate(value) {
  const year = value.getFullYear();
  const month = String(value.getMonth() + 1).padStart(2, "0");
  const day = String(value.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function sanitizeFilePart(value = "") {
  const cleaned = String(value).trim().replace(/[^a-z0-9_-]+/gi, "");
  return cleaned || "User";
}

function createKeyValueRows(entries) {
  return entries.map(([label, value]) => [label, value || "No data available"]);
}

function createEmptyRows(columnCount, message = "No data available") {
  return [Array.from({ length: columnCount }, (_, index) => (index === 0 ? message : ""))];
}

function renderSectionTitle(doc, title, top) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(16, 32, 58);
  doc.text(title, 14, top);
}

function renderTable(doc, { title, startY, head, body, theme = "grid", columnStyles }) {
  renderSectionTitle(doc, title, startY);

  autoTable(doc, {
    startY: startY + 4,
    head,
    body,
    theme,
    margin: { left: 14, right: 14 },
    styles: {
      font: "helvetica",
      fontSize: 10,
      cellPadding: 3,
      lineColor: [222, 226, 235],
      lineWidth: 0.4,
      textColor: [16, 32, 58],
      overflow: "linebreak"
    },
    headStyles: {
      fillColor: [10, 102, 194],
      textColor: [255, 255, 255],
      fontStyle: "bold"
    },
    alternateRowStyles: {
      fillColor: [247, 249, 252]
    },
    columnStyles
  });

  return doc.lastAutoTable.finalY + 10;
}

function addPageDecorators(doc, generatedAt) {
  const pageCount = doc.getNumberOfPages();

  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    doc.setDrawColor(222, 226, 235);
    doc.line(14, 18, pageWidth - 14, 18);
    doc.line(14, pageHeight - 14, pageWidth - 14, pageHeight - 14);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(10, 102, 194);
    doc.text("DevDNA", 14, 12);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(82, 96, 118);
    doc.text("Developer Progress Report", 14, 16);

    doc.setFontSize(9);
    doc.text("Generated by DevDNA", 14, pageHeight - 8);
    doc.text(
      `${formatDateValue(generatedAt)} | ${formatTimeValue(generatedAt)}`,
      pageWidth / 2,
      pageHeight - 8,
      { align: "center" }
    );
    doc.text(`Page ${page}`, pageWidth - 14, pageHeight - 8, { align: "right" });
  }
}

export function generateDevDNAPdfReport({
  profile,
  skills,
  goals,
  projects,
  github,
  analytics
}) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const generatedAt = new Date();

  let cursorY = 28;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(82, 96, 118);
  doc.text(
    "A professional summary of developer growth, portfolio delivery, and GitHub activity.",
    14,
    cursorY
  );
  cursorY += 8;

  cursorY = renderTable(doc, {
    title: "User Information",
    startY: cursorY,
    head: [["Field", "Value"]],
    body: createKeyValueRows([
      ["Name", profile?.full_name || "No data available"],
      ["Role", profile?.role || "No data available"],
      ["GitHub Username", profile?.github_username || "No data available"]
    ]),
    columnStyles: {
      0: { cellWidth: 48, fontStyle: "bold" },
      1: { cellWidth: "auto" }
    }
  });

  cursorY = renderTable(doc, {
    title: "Skills Summary",
    startY: cursorY,
    head: [["Metric", "Value"]],
    body: createKeyValueRows([
      ["Total Skills", String(analytics.totalSkills)],
      ["Average Progress", `${analytics.averageProgress}%`]
    ]),
    columnStyles: {
      0: { cellWidth: 48, fontStyle: "bold" },
      1: { cellWidth: "auto" }
    }
  });

  cursorY = renderTable(doc, {
    title: "Skills List",
    startY: cursorY,
    head: [["Skill", "Level", "Progress", "Current Focus"]],
    body: skills.length
      ? skills.map((skill) => [
          skill.name || "No data available",
          skill.level || "No data available",
          `${Number(skill.progress || 0)}%`,
          skill.focus || "No data available"
        ])
      : createEmptyRows(4),
    columnStyles: {
      0: { cellWidth: 44 },
      1: { cellWidth: 28 },
      2: { cellWidth: 24 },
      3: { cellWidth: "auto" }
    }
  });

  cursorY = renderTable(doc, {
    title: "Learning Goals Summary",
    startY: cursorY,
    head: [["Metric", "Value"]],
    body: createKeyValueRows([
      ["Total Goals", String(analytics.totalGoals)],
      ["Completed Goals", String(analytics.completedGoals)],
      ["In Progress Goals", String(analytics.inProgressGoals)],
      ["Pending Goals", String(analytics.pendingGoals)]
    ]),
    columnStyles: {
      0: { cellWidth: 56, fontStyle: "bold" },
      1: { cellWidth: "auto" }
    }
  });

  cursorY = renderTable(doc, {
    title: "Projects Summary",
    startY: cursorY,
    head: [["Metric", "Value"]],
    body: createKeyValueRows([
      ["Total Projects", String(analytics.totalProjects)],
      ["Healthy Projects", String(analytics.healthyProjects)],
      ["Warning Projects", String(analytics.warningProjects)],
      ["Critical Projects", String(analytics.criticalProjects)]
    ]),
    columnStyles: {
      0: { cellWidth: 56, fontStyle: "bold" },
      1: { cellWidth: "auto" }
    }
  });

  cursorY = renderTable(doc, {
    title: "GitHub Summary",
    startY: cursorY,
    head: [["Metric", "Value"]],
    body: createKeyValueRows([
      ["Repository Count", github?.error ? "No data available" : String(github?.stats?.repoCount ?? 0)],
      ["Followers", github?.error ? "No data available" : String(github?.profile?.followers ?? "No data available")],
      ["Following", github?.error ? "No data available" : String(github?.profile?.following ?? "No data available")],
      ["Recent Activity", github?.error ? "No data available" : String(github?.stats?.recentEvents ?? 0)]
    ]),
    columnStyles: {
      0: { cellWidth: 52, fontStyle: "bold" },
      1: { cellWidth: "auto" }
    }
  });

  renderTable(doc, {
    title: "Analytics Summary",
    startY: cursorY,
    head: [["Score", "Value", "Detail"]],
    body: analytics.overallProgressData.length
      ? analytics.overallProgressData.map((item) => [
          item.name,
          `${item.value}%`,
          item.detail || "No data available"
        ])
      : createEmptyRows(3),
    columnStyles: {
      0: { cellWidth: 36, fontStyle: "bold" },
      1: { cellWidth: 28 },
      2: { cellWidth: "auto" }
    }
  });

  addPageDecorators(doc, generatedAt);

  const usernamePart = sanitizeFilePart(
    profile?.github_username || profile?.full_name || "User"
  );
  const fileName = `DevDNA_Report_${usernamePart}_${formatFileDate(generatedAt)}.pdf`;

  doc.save(fileName);

  return fileName;
}
